football_analytics:
  target: dev
  outputs:
    dev:
      type: clickhouse
      schema: "{{ env_var('CLICKHOUSE_DB', 'football') }}"
      host: "{{ env_var('CLICKHOUSE_HOST', 'localhost') }}"
      port: "{{ env_var('CLICKHOUSE_PORT', '8124') | int }}"
      user: default
      password: ""
      secure: false
