target:
- target
continuous_cols:
- home_form_5_ppg
- away_form_5_ppg
- home_xg_for_avg_last_5
- away_xg_for_avg_last_5
- xg_diff
- shots_on_target_diff
- possession_diff
- home_attack_strength
- away_defence_weakness
- home_elo_diff
- h2h_home_win_rate
- home_rest_days
- away_rest_days
- rest_days_diff
- position_diff
- h2h_matches_played
categorical_cols: []
date_columns: []
encode_date_columns: true
validation_split: 0.2
continuous_feature_transform: null
normalize_continuous_features: true
quantile_noise: 0
num_workers: 0
pin_memory: true
handle_unknown_categories: true
handle_missing_values: true
pickle_protocol: 2
dataloader_kwargs: {}
task: classification
head: LinearHead
head_config:
  layers: ''
embedding_dims: []
embedding_dropout: 0.0
batch_norm_continuous_input: true
learning_rate: 0.001
loss: CrossEntropyLoss
metrics:
- accuracy
metrics_prob_input:
- false
metrics_params:
- sub_params_list:
  - task: multiclass
    num_classes: 3
    top_k: 1
target_range: null
virtual_batch_size: null
seed: 42
_module_src: models.ft_transformer
_model_name: FTTransformerModel
_backbone_name: FTTransformerBackbone
_config_name: FTTransformerConfig
input_embed_dim: 32
embedding_initialization: kaiming_uniform
embedding_bias: true
share_embedding: false
share_embedding_strategy: fraction
shared_embedding_fraction: 0.25
attn_feature_importance: true
num_heads: 8
num_attn_blocks: 6
transformer_head_dim: null
attn_dropout: 0.1
add_norm_dropout: 0.1
ff_dropout: 0.1
ff_hidden_multiplier: 4
transformer_activation: GEGLU
batch_size: 128
data_aware_init_batch_size: 2000
fast_dev_run: false
max_epochs: 5
min_epochs: 1
max_time: null
accelerator: cpu
devices: 1
devices_list: null
accumulate_grad_batches: 1
auto_lr_find: false
auto_select_gpus: false
check_val_every_n_epoch: 1
gradient_clip_val: 0.0
overfit_batches: 0.0
deterministic: false
profiler: null
early_stopping: null
early_stopping_min_delta: 0.001
early_stopping_mode: min
early_stopping_patience: 3
early_stopping_kwargs: {}
checkpoints: null
checkpoints_path: saved_models
checkpoints_every_n_epochs: 1
checkpoints_name: null
checkpoints_mode: min
checkpoints_save_top_k: 1
checkpoints_kwargs: {}
load_best: false
track_grad_norm: -1
progress_bar: none
precision: '32'
trainer_kwargs: {}
optimizer: Adam
optimizer_params: {}
lr_scheduler: null
lr_scheduler_params: {}
lr_scheduler_monitor_metric: valid_loss
lr_scheduler_interval: epoch
categorical_dim: 0
continuous_dim: 16
output_dim: 3
output_cardinality:
- 3
categorical_cardinality: []
embedded_cat_dim: 0
